name: bpftrace tests

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set image tag value
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - name: Build and Load Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: build/Dockerfile
          tags: bdtrace:${{ steps.vars.outputs.tag }}
          load: true

      - name: Run Tests
        run: docker run --rm bdtrace:${{ steps.vars.outputs.tag }}
